# Copyright 2021 BlackRock, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
trigger:
  branches:
    include:
      - "*"

schedules:
  - cron: "12 3 * * 1,4"
    displayName: Bi-weekly check
    branches:
      include:
        - master
    always: true

pool:
  name: default
  demands:
    - python3


stages:
  - stage: install_deps
    dependsOn: []
    displayName: "CI"
    jobs:
      - job: static_analysis
        displayName: Static Analysis
        steps:
          - template: ../templates/pyenv_install.yml
          - script: |
              set +x
              which pip
              which python
              echo "##vso[task.setvariable variable=PYTHONPATH].env:${PYTHONPATH}"
              echo "##vso[task.setvariable variable=PATH].env/bin:${PATH}"
              make env # extra_pip_flags="--target .env"
            displayName: pip install
          - script: |
              echo $PYTHONPATH
              echo $PATH
              make lint
            displayName: lint
      - job: tests
        displayName: Tests
        steps:
          - template: ../templates/pyenv_install.yml
          - script: |
              set +x
              which pip
              which python
              echo "##vso[task.setvariable variable=PYTHONPATH].env:${PYTHONPATH}"
              echo "##vso[task.setvariable variable=PATH].env/bin:${PATH}"
              make env extra_pip_flags="--target .env"
            displayName: pip install
          - script: |
              echo $PYTHONPATH
              echo $PATH
              make test
            displayName: test
